### PR TITLE
Fixed failing MSVC build

### PR DESCRIPTION
**Pull request by pzychotic**
## Pull Request Type

- [ ] GitHub Workflow changes
- [ ] Documentation or Wiki changes
- [x] Build and Dependency changes
- [ ] Runtime changes
  - [ ] Render changes
  - [ ] Audio changes
  - [ ] Input changes
  - [ ] Network changes
  - [ ] Other changes

### Description

When starting from a completely new/empty build directory where `$<TARGET_FILE_DIR:Descent3>` doesn't exist yet, the copy command for `LICENSE` will create a **file** named `Debug` or `Release`, depending on the current configuration, in the Descent3 directory. This then prevents the creation of the output directory for the Descent3 target with the same name and thus failing the build.
I'm not quite sure why this doesn't happen on our CI builds. Maybe it's some difference between IDE and command line builds or just luck in case of parallel builds...

### Checklist

- [x] I have tested my changes locally and verified that they work as intended.
- [x] I have documented any new or modified functionality.
- [x] I have reviewed the changes to ensure they do not introduce any unnecessary complexity or duplicate code.
- [x] I understand that by submitting this pull request, I am agreeing to license my contributions under the project's license.

### CODE REVIEW

**Comment by Jayman2000** [comment]
Could you provide steps to reproduce this issue on the main branch? I want to test out this PR, but I haven’t figured out how to make CMake to create the `Debug` or `Release` file.

---

> When starting from a completely new/empty build directory where `$<TARGET_FILE_DIR:Descent3>` doesn't exist yet, the copy command for `LICENSE` will create a **file** named `Debug` or `Release`, depending on the current configuration, in the Descent3 directory. This then prevents the creation of the output directory for the Descent3 target with the same name and thus failing the build.

I would put this into your commit message.

**Comment by pzychotic** [comment]
> Could you provide steps to reproduce this issue on the main branch? I want to test out this PR, but I haven’t figured out how to make CMake to create the `Debug` or `Release` file.

The problem happens on compile time when the custom target to copy the LICENSE file gets executed.

Steps to reproduce:
- delete your current build directory
- run CMake to generate the Descent3.sln
- open Descent3.sln in VS
- build solution

**Comment by winterheart** [comment]
Hello. 
Better way is replace all custom commands (related to license files) with `install` command like main license file (you can even add license files into root CMakeLists.txt install directive):

```
install(FILES README.md LICENSE <additional files here> DESTINATION ${CMAKE_INSTALL_DOCDIR})
```

**Comment by Jayman2000** [comment]
> Steps to reproduce:
> 
> * delete your current build directory
> 
> * run CMake to generate the Descent3.sln
> 
> * open Descent3.sln in VS
> 
> * build solution

I was able to reproduce this problem using those steps, but unfortunately, I can’t get it to reproduce consistently. I was also able to reproduce it by running `cmake --build --preset win32 -j 0`.

**Comment by pzychotic** [comment]
> > Steps to reproduce:
> > 
> > * delete your current build directory
> > * run CMake to generate the Descent3.sln
> > * open Descent3.sln in VS
> > * build solution
> 
> I was able to reproduce this problem using those steps, but unfortunately, I can’t get it to reproduce consistently. I was also able to reproduce it by running `cmake --build --preset win32 -j 0`.

Glad you can reproduce it and it's not just me. From the VS IDE I was hitting it consistently.

**Comment by pzychotic** [comment]
> Hello. Better way is replace all custom commands (related to license files) with `install` command like main license file (you can even add license files into root CMakeLists.txt install directive):
> 
> ```
> install(FILES README.md LICENSE <additional files here> DESTINATION ${CMAKE_INSTALL_DOCDIR})
> ```

This sounds like sensible solution, too.
If some wants to give a shot, be my guest. I'll probably can't get to it soon'ish.

**Pull request closed without merging**
