### PR TITLE
DallasFunc user_var object: fix GCC 9.4 compilation

### PR DESCRIPTION
**Pull request by Lgt2x**
## Pull Request Type

- [ ] GitHub Workflow changes
- [ ] Documentation or Wiki changes
- [x] Build and Dependency changes
- [ ] Runtime changes
  - [ ] Render changes
  - [ ] Audio changes
  - [ ] Input changes
  - [ ] Network changes
  - [ ] Other changes

### Description

GCC 9/Ubuntu 20.04 that does not implement P2162R2, allowing to use std::visit on classes inheriting from std::variant. This addresses the issue by implementing our own visit function performing a static cast to the parent variant type

### Related Issues

Fixup #573

### Checklist

- [x] I have tested my changes locally and verified that they work as intended.
- [x] I have documented any new or modified functionality.
- [x] I have reviewed the changes to ensure they do not introduce any unnecessary complexity or duplicate code.
- [x] I understand that by submitting this pull request, I am agreeing to license my contributions under the project's license.

### CODE REVIEW

**Comment by winterheart** [comment]
If we going to support Ubuntu 20.04 LTS toolchain, then we probably need add it our GitHub CI matrix.

**Comment by Lgt2x** [comment]
> If we going to support Ubuntu 20.04 LTS toolchain, then we probably need add it our GitHub CI matrix.

You're right. It will be EOL by April 2025, but apparently many people still use it as a daily driver

**Comment by jengelh** [comment]
Mentioning P2162 was helpful in optimizing your 592. I have a "zero-cost" version in #593. (We can do without the extra visit() member function.)

**Comment by Lgt2x** [comment]
Replaced by #593

**Pull request closed without merging**
