### PR TITLE
Add a copy of the GPL to CI artifacts

### LINKED ISSUE #276: CI artifacts are missing a copy of the GPL
[The GPL requires that you include a copy of the GPL with every copy of programs that are released under the GPL.](https://www.gnu.org/licenses/gpl-faq.en.html#WhyMustIInclude) It looks like the CI artifacts don’t include a copy of the GPL.

### PR DESCRIPTION
**Pull request by Jayman2000**
## Pull Request Type

- [x] GitHub Workflow changes
- [ ] Documentation or Wiki changes
- [ ] Build and Dependency changes
- [ ] Runtime changes
  - [ ] Render changes
  - [ ] Audio changes
  - [ ] Input changes
  - [ ] Network changes
  - [ ] Other changes

### Description

[The GPL requires that you include a copy of the GPL with every copy of programs that are released under the GPL][1]. Before this change, CI artifacts didn’t include a copy of the GPL.

[1]: https://www.gnu.org/licenses/gpl-faq.en.html#WhyMustIInclude

### Related Issues

Fixes #276

### Checklist

- [x] I have tested my changes ~~locally~~ _in CI_ and verified that they work as intended.
- [ ] I have documented any new or modified functionality.
- [x] I have reviewed the changes to ensure they do not introduce any unnecessary complexity or duplicate code.
- [x] I understand that by submitting this pull request, I am agreeing to license my contributions under the project's license.

### CODE REVIEW

**Comment by JeodC** [comment]
Thank you, but we will take care of this in #242 which will be resolved sometime this weekend.

**Comment by Lgt2x** [comment]
CI needs [this change](https://github.com/DescentDevelopers/Descent3/pull/257/files#diff-5c3fa597431eda03ac3339ae6bf7f05e1a50d6fc7333679ec38e21b337cb6721L16) to run so we can check artifact :)

**Comment by Jayman2000** [comment]
> CI needs [this change](https://github.com/DescentDevelopers/Descent3/pull/257/files#diff-5c3fa597431eda03ac3339ae6bf7f05e1a50d6fc7333679ec38e21b337cb6721L16) to run so we can check artifact :)

That’s kind of annoying. Luckily, I was able to manually trigger CI for this PR here: <https://github.com/Jayman2000/Descent3-pr/actions/runs/8944229931>

**Comment by Lgt2x** [comment]
The changes mentioned have just been merged, you can rebase to hopefully have artifacts

**Comment by JeodC** [comment]
Superseded by #284

**Pull request closed without merging**
