### PR TITLE
Use vector instead of array, and proper referencing

### PR DESCRIPTION
**Pull request by tophyr**
Instead of using a hardcode-size array for app instances, use a vector instead. This cleans up some bad referencing as well.

### CODE REVIEW

**Comment by bryanperris** [comment]
See my closed issue: https://github.com/DescentDevelopers/Descent3/issues/112

**Comment by Lgt2x** [comment]
CMakeLists.txt conflict needs resolved. Does this PR actually solve any compilation or runtime problem ?

**Comment by winterheart** [comment]
CMakeLists.txt changes are not related and failing Windows build. Please remove them from PR.

**Comment by Lgt2x** [comment]
In addition, please refrain from refactoring complete files when not absolutely necessary. We don't have a full testing pipeline right now, we're just trying really hard to get the base game working, and full file refactors can easily introduce problems. I'd prefer a simpler fix for getting Asan to work if possible. Thanks!

**Pull request closed without merging**
