### PR TITLE
Support -nosound option for movie playbacks

### PR DESCRIPTION
**Pull request by Lgt2x**
## Pull Request Type

- [ ] GitHub Workflow changes
- [ ] Documentation or Wiki changes
- [x] Build and Dependency changes
- [ ] Runtime changes
  - [ ] Render changes
  - [ ] Audio changes
  - [ ] Input changes
  - [ ] Network changes
  - [x] Other changes

### Description
Support -nosound option for movie playbacks

### Related Issues

Improves on #289

### CODE REVIEW

**Comment by winterheart** [comment]
Better to move `FindArg("-nosound")` to d3movie.cpp's `mve_InitSound()` like this

```cpp

bool mve_InitSound() {
  int nosound = FindArg("-nosound");
  // Probably refactor MVE_sndInit a little to clean up this
  MVE_sndInit(nosound == 1 ? 0 : 1);
  return true;
}
```

**Comment by Lgt2x** [comment]
> Better to move `FindArg("-nosound")` to d3movie.cpp's `mve_InitSound()` like this
> 
> ```c++
> bool mve_InitSound() {
>   int nosound = FindArg("-nosound");
>   // Probably refactor MVE_sndInit a little to clean up this
>   MVE_sndInit(nosound == 1 ? 0 : 1);
>   return true;
> }
> ```

ok, I moved the check 1 level higher. I also changed the function signature to be more explicit

**Comment by Lgt2x** [comment]
@winterheart need re-review

**Comment by winterheart** [comment]
Works as expected.

**Pull request merged**
