### PR TITLE
Add release flow to GitHub Actions

### PR DESCRIPTION
**Pull request by winterheart**
Initial support to automate release flow. Now after git tag of specific commit GitHub Actions will create a draft entry of release (named by tag) with source code package on it.

## Pull Request Type

- [x] GitHub Workflow changes
- [ ] Documentation or Wiki changes
- [ ] Build and Dependency changes
- [ ] Runtime changes
  - [ ] Render changes
  - [ ] Audio changes
  - [ ] Input changes
  - [ ] Network changes
  - [ ] Other changes

### Related Issues

Related to #506.

### Checklist

- [x] I have tested my changes locally and verified that they work as intended.
- [x] I have documented any new or modified functionality.
- [x] I have reviewed the changes to ensure they do not introduce any unnecessary complexity or duplicate code.
- [x] I understand that by submitting this pull request, I am agreeing to license my contributions under the project's license.

### CODE REVIEW

**Comment by Lgt2x** [comment]
It looks like GitHub already creates a source archive when you create a release https://github.com/Lgt2x/Descent3/releases/tag/test

**Comment by winterheart** [comment]
This is autogenerated source from git. Mine flow creates prepared source tarball with generated `git-hash.txt` that will be used on environment without git history.

**Comment by Lgt2x** [comment]
I don't see any artifacts though ? https://github.com/Lgt2x/Descent3/actions/runs/10357718112

**Comment by winterheart** [comment]
You should see in Releases new release named by tag, "test2". Pipeline configured to mark it as draft and it's visible only to  owner of repository.
Here example how it's looks on manually published release: https://github.com/winterheart/Descent3/releases/tag/test

**Comment by Lgt2x** [comment]
Ok I get it now. The archive looks good to me

**Review by Lgt2x — APPROVED** [review]

**Pull request merged**
