### PR TITLE
Fix endline characters

### LINKED ISSUE #129: Inconsistent line endings
Some files in this repo use LF line endings, and some files in this repo use CRLF line endings. [I created a script that will calculate how many files use LF line endings and how many files use CRLF line endings.](https://gist.github.com/Jayman2000/f8e1d010401c0f19125729546fac199b) Here’s what the script says when you run it on the most recent commit (07d988e194cfdaf87a86d798bb423af0ff25d096):

```
Total number of files that use LF line endings: 1,491 (86%)
Total number of files that use CRLF line endings: 62 (3%)
Total number of files: 1,724
```

It would be nice if all of the files in this repo used the same line endings. Are there any files that need to use LFs or need to use CRLFs? For example, I can see that `scripts/data/linuxfullhog/d3i.str` uses CRLFs. Would using LFs in that file break anything?

### PR DESCRIPTION
**Pull request by GravisZro**
Replace \r\n with \n.
```
#!/bin/sh
for filename in $(find)
do
  encoding=$(file -b --mime-encoding $filename)
  if [ "$encoding" = "us-ascii" ] ||
     [ "$encoding" = "iso-8859-1" ]; then
    echo fixing ${filename}
    sed 's/\r$//' ${filename} > ${filename}.lf
    mv ${filename}.lf ${filename}
done
```
Fixes #129

### CODE REVIEW

**Comment by GravisZro** [comment]
The file encodings are not altered by this patch.

**Comment by GravisZro** [comment]
@Lgt2x By properly generated do you mean the game or the editor?

**Comment by Lgt2x** [comment]
the game when creating the HOGs

**Comment by JeodC** [comment]
I just played through Level 5 with this build, I think it's fine.

**Pull request closed without merging**
