### PR TITLE
Fix crash in hlsSystem::ComputePlayInfo(), #141

### PR DESCRIPTION
**Pull request by DanielGibson**
sound_seg was -1, which crashes in BOA_INDEX(sound_seg) on 64bit platforms (by pure luck it doesn't seem to crash on 32bit platforms)

See https://github.com/DescentDevelopers/Descent3/issues/141#issuecomment-2071219212 for more details.

I still am not 100% sure if this is the proper fix or just hides another bug.
@kevinbentley is it expected that `objp->roomnum` can be `-1` in that function, or does this indicate a bug elsewhere, of that object wasn't initialized properly?

### CODE REVIEW

**Comment by Lgt2x** [comment]
One such PR has already been merged (#140), we'll likely find more bugs of this kind in old 32bit code

**Comment by JeodC** [comment]
The artifact in this pull should be playtested.

**Comment by DanielGibson** [comment]
converted it to a draft, because it needs testing and I wanna check if it makes sense to catch this problem earler in the backtrace

for the record, the backtrace was:

```
#0  0x000000000067747e in hlsSystem::ComputePlayInfo (this=0x1339f20 <Sound_system>, sound_obj_index=2, virtual_pos=0x7fffffffbd70, virtual_vel=0x7fffffffbd64, 
    adjusted_volume=0x7fffffffbd60) at /home/bperris/base/dev/Descent3/sndlib/hlsoundlib.cpp:925
#1  0x0000000000677f1d in hlsSystem::Emulate3dSound (this=0x1339f20 <Sound_system>, sound_obj_index=2)
    at /home/bperris/base/dev/Descent3/sndlib/hlsoundlib.cpp:1024
#2  0x00000000006789b8 in hlsSystem::Play3dSound (this=0x1339f20 <Sound_system>, sound_index=126, cur_pos=0x7fffffffbe40, cur_obj=0x8fe8b0 <Objects+39312>, 
    priority=1, volume=1, flags=0, offset=0) at /home/bperris/base/dev/Descent3/sndlib/hlsoundlib.cpp:1157
#3  0x0000000000678269 in hlsSystem::Play3dSound (this=0x1339f20 <Sound_system>, sound_index=126, priority=1, cur_obj=0x8fe8b0 <Objects+39312>, volume=1, flags=0, 
    offset=0) at /home/bperris/base/dev/Descent3/sndlib/hlsoundlib.cpp:1065
#4  0x0000000000412429 in AIInit (obj=0x8fe8b0 <Objects+39312>, ai_class=0 '\000', ai_type=2 '\002', ai_movement=1 '\001')
    at /home/bperris/base/dev/Descent3/Descent3/AImain.cpp:3741
#5  0x0000000000545c7d in ObjInitGeneric (objp=0x8fe8b0 <Objects+39312>, reinit=false) at /home/bperris/base/dev/Descent3/Descent3/ObjInit.cpp:810
#6  0x0000000000546b97 in ObjInitTypeSpecific (objp=0x8fe8b0 <Objects+39312>, reinitializing=false) at /home/bperris/base/dev/Descent3/Descent3/ObjInit.cpp:1117
#7  0x0000000000546ed3 in ObjInit (objp=0x8fe8b0 <Objects+39312>, type=2, id=102, handle=2087, pos=0x7fffffffc034, creation_time=0, parent_handle=-1)
    at /home/bperris/base/dev/Descent3/Descent3/ObjInit.cpp:1206
#8  0x00000000004c21c6 in ReadObject (ifile=0x27de7e0, objp=0x8fe8b0 <Objects+39312>, handle=2087, fileversion=127)
    at /home/bperris/base/dev/Descent3/Descent3/LoadLevel.cpp:1667
#9  0x00000000004c9b58 in LoadLevel (filename=0x169ad50 "Level2.d3l", cb_fn=0x0) at /home/bperris/base/dev/Descent3/Descent3/LoadLevel.cpp:3816
#10 0x00000000004dbd6f in LoadMissionLevel (level=2) at /home/bperris/base/dev/Descent3/Descent3/Mission.cpp:1296
#11 0x000000000049201d in LoadAndStartCurrentLevel () at /home/bperris/base/dev/Descent3/Descent3/gamesequence.cpp:1706
#12 0x0000000000491011 in GameSequencer () at /home/bperris/base/dev/Descent3/Descent3/gamesequence.cpp:1199
#13 0x0000000000472187 in PlayGame () at /home/bperris/base/dev/Descent3/Descent3/game.cpp:832
#14 0x0000000000464a1c in MainLoop () at /home/bperris/base/dev/Descent3/Descent3/descent.cpp:621
#15 0x00000000004648b8 in Descent3 () at /home/bperris/base/dev/Descent3/Descent3/descent.cpp:571
#16 0x00000000005e6df1 in oeD3LnxApp::run (this=0x7fffffffd4a0) at /home/bperris/base/dev/Descent3/Descent3/lnxmain.cpp:255
#17 0x00000000005e6d25 in main (argc=1, argv=0x7fffffffd6a8) at /home/bperris/base/dev/Descent3/Descent3/lnxmain.cpp:755
```

**Comment by DanielGibson** [comment]
I added an early-out for that roomnum == -1 case which not just avoids unnecessary computation but should also prevent problems with looping sounds remaining half-initialized, see https://github.com/DescentDevelopers/Descent3/issues/141#issuecomment-2073397886.

I think this is ready for review, but before merging it should be tested more, also on Win32 where the game should generally work ok - on 64bit Linux it's still pretty buggy, at least on my machine - it doesn't crash while playing, but mouse input is wonky and in the Pilot Training mission I can't get out of the first room (but maybe it's just me not knowing how this game works :-D)

**Comment by JeodC** [comment]
No immediate problems on windows. All sounds seem to be playing properly.

**Comment by winterheart** [comment]
I would propose to change `TERRAIN_REGION` in terrain.h to handle case with -1:

```c
inline int TERRAIN_REGION(int x) {
  if (x != -1) return ((Terrain_seg[0x7FFFFFFF & x].flags & TFM_REGION_MASK) >> 5);
  return 0;
}
```
or as macro:

```c
#define TERRAIN_REGION(x) (((x) != -1) ? ((Terrain_seg[0x7FFFFFFF & (x)].flags & TFM_REGION_MASK) >> 5) : 0)
```

**Comment by DanielGibson** [comment]
The only sensible change to TERRAIN_REGION() would be to add an ASSERT() that (in debug builds) makes the program abort if an invalid index is passed, so other similar issues are found more easily.

**Comment by DanielGibson** [comment]
I did add such an ASSERT to TERRAIN_REGION now.
Tested it a bit, still works.

I think this is ready for merging, or at least a proper review :)

**Comment by JeodC** [comment]
I think enough debate has been done on the matter. This pull looks like it gets to the root of the problem, and continuing to go back and forth about it is just demoralizing to whoever gets involved with it.

Thanks for your work on this one.

**Pull request merged**
