### PR TITLE
Use proper byteswapping functions

### PR DESCRIPTION
**Pull request by GravisZro**
Converts INTEL_* and MOTOROLA_* macros to use the proper functions.

From POSIX for networking conversions:
* host to network (16-bit) : htons()
* host to network (32-bit) : htonl()
* network to host (16-bit) : ntohs()
* network to host (32-bit) : ntohl()

From GNU for endian conversions:
* host to little endian (16-bit) : htole16()
* host to little endian (32-bit) : htole32()
* host to little endian (64-bit) : htole64()
* little endian to host (16-bit) : le16toh()
* little endian to host (32-bit) : le32toh()
* little endian to host (64-bit) : le64toh()

### CODE REVIEW

**Comment by winterheart** [comment]
These functions are not C99 compatible, there no way to implement in Windows platform. I'm already working on C++ cross-platform byteswap functions, just allow me some time to properly implement them in code.

**Comment by GravisZro** [comment]
> These functions are not C99 compatible, there no way to implement in Windows platform.

I don't understand this comment at all because everything seems contrary to the claims made.

**Comment by winterheart** [comment]
Please see #165.

**Comment by Arcnor** [comment]
Closing in favour of #165

**Pull request closed without merging**
