### PR TITLE
[CI] Use same job for both Debug and Release builds

### PR DESCRIPTION
**Pull request by danra**
Making use of CMake's multi-config generators which we're using. 
Simpler and more efficient, halves number of jobs.

### CODE REVIEW

**Comment by Lgt2x** [comment]
Good idea, but artifacts don't seem correct

**Comment by JeodC** [comment]
Right, artifacts only need the Debug and Release folders.

image

**Comment by JeodC** [comment]
No artifacts were found: https://github.com/DescentDevelopers/Descent3/actions/runs/8773591912

**Comment by danra** [comment]
Yes I see :)
Prodding it until it works

**Comment by danra** [comment]
Looks good now

**Comment by JeodC** [comment]
Perfect, thank you.

**Pull request merged**
