### PR TITLE
Fix undefined behavior in memory allocation

### PR DESCRIPTION
**Pull request by sebholt**
## Pull Request Type

- [ ] GitHub Workflow changes
- [ ] Documentation or Wiki changes
- [ ] Build and Dependency changes
- [x] Runtime changes
  - [ ] Render changes
  - [ ] Audio changes
  - [ ] Input changes
  - [ ] Network changes
  - [x] Other changes

### Description

Currently `mem_rmalloc` uses `std::malloc` for memory allocation and the deallocation is performed in `mem_free`
which calls `::free`. This does seem to work but is **undefined behavior** because memory allocated with `std::malloc`
should be freed with `std::free` not `::free`.

We should use either 
- the C interface: `::malloc` and `::free`, or
- C++ interface: `std::malloc` and `std::free`.

The `mem_malloc/mem_free` functions already use the C interface so it makes sense to let `mem_rmalloc` simply call
`mem_malloc` instead of `std::malloc` directly. There's also no speed difference because everything is inline or a macro. 

This changes the `mem_rmalloc` function to call `mem_malloc` instead of `std::malloc` to match the `mem_free` call.

### Checklist

- [x] I have tested my changes locally and verified that they work as intended.
- [x] I have documented any new or modified functionality.
- [x] I have reviewed the changes to ensure they do not introduce any unnecessary complexity or duplicate code.
- [x] I understand that by submitting this pull request, I am agreeing to license my contributions under the project's license.

### CODE REVIEW

**Comment by pzychotic** [comment]
LGTM
But since this code was just recently introduced by @jengelh, I would like to get his opinion before merging.

**Comment by sebholt** [comment]
Ok. I've updated the PR description to make the issue more clear.

**Comment by jengelh** [comment]
It's a sound argument.

**Comment by pzychotic** [comment]
Thanks both of you!

**Pull request merged**
