### PR TITLE
Fixed inconsistent use of memory management functions

### LINKED ISSUE #444: [Runtime Issue]: Quitting the game causes “Debug Assertion Failed! `_CrtlsValidHeapPointer(block)`”
### Build Version

v1.5 a059b14677204681030d41706b8296962cbb9be8

### Operating System Environment

- [ ] Microsoft Windows (32-bit)
- [X] Microsoft Windows (64-bit)
- [ ] Mac OS X
- [ ] Linux (specify distribution and version below)

### CPU Environment

- [ ] x86 (32-bit Intel/AMD)
- [X] x86\_64 (64-bit Intel/AMD)
- [ ] ARM (32-bit)
- [ ] ARM64 (64-bit; sometimes called AArch64)
- [ ] Other (RISC V, PPC...)

### Game Modes Affected

- [X] Single player
- [X] Anarchy
- [X] Hyper-Anarchy
- [X] Robo-Anarchy
- [X] Team Anarchy
- [X] Capture the Flag
- [X] Bounty
- [X] Entropy
- [X] Hoard
- [X] Monsterball
- [X] Cooperative

### Game Environment

I’m using game data from the Windows Dual-Jewel version of Descent 3 v1.4.

### Description

When I quit the game, this message appears:

Microsoft Visual C++ Runtime Library&NewLine;&NewLine;Debug Assertion Failed!&NewLine;&NewLine;Program: …y mine\Descent3\main\builds\win32\Descent3\Debug\Descent3.exe&NewLine;File: minkernel\crts\ucrt\src\appcrt\heap\debug_heap.cpp&NewLine;Line: 904&NewLine;&NewLine;Expression: _CrtlsValidHeapPointer(block)&NewLine;&NewLine;For information on how your program can cause an assertion failure, see the Visual C++ documentation on asserts.&NewLine;&NewLine;(Press Retry to debug the application)&NewLine;&NewLine;Choose one of these options: Abort, Retry, Ignore

### Regression Status

I don’t know.

### Steps to Reproduce

1. Run `Descent3 -nointro -pilot <pilot-name>`
2. Wait for the main menu to load.
3. Press <kbd>Q</kbd>.
4. Press <kbd>Y</kbd>.

### PR DESCRIPTION
**Pull request by pzychotic**
## Pull Request Type

- [ ] GitHub Workflow changes
- [ ] Documentation or Wiki changes
- [x] Build and Dependency changes
- [ ] Runtime changes
  - [ ] Render changes
  - [ ] Audio changes
  - [ ] Input changes
  - [ ] Network changes
  - [ ] Other changes

### Description

Before #436 `MEM_USE_RTL` was a define in _lib/mem.h_ that could be uncommented to change the memory management functions. So every library including _mem.h_ was agreeing on the same memory functions.

By changing this to a CMake option and only enabling it on the Descent3 target, all other libraries would never activate this preprocessor definition when the option is enabled and therefore use different memory functions.

Allocating memory from any code of a library and freeing this memory from code compiled as part of Descent3, or vice versa, will result in memory corruption.

### Related Issues

Fixes #444

### Checklist

- [x] I have tested my changes locally and verified that they work as intended.
- [x] I have documented any new or modified functionality.
- [x] I have reviewed the changes to ensure they do not introduce any unnecessary complexity or duplicate code.
- [x] I understand that by submitting this pull request, I am agreeing to license my contributions under the project's license.

### CODE REVIEW

**Comment by winterheart** [comment]
Probably is better to move `target_compile_definitions` into `mem` module, where it should belong to.

**Comment by Lgt2x** [comment]
Ugh I missed that at review. I agree that it should be a `target_compile_definitions` though

**Comment by pzychotic** [comment]
I understand why you would want to do that, but...

In order for this to work, every library that includes _mem.h_ would also need a dependency to the `mem` target through `target_link_libraries` in order for that define to propagate correctly. Not a single library does that currently. This means changing close to 20 of our roughly 50 libraries.

And if than someone refactors parts of the project or includes mem.h in another lib that doesn't have the dependency yet, we might not even realize that we end up with the same runtime problems we got now.

Unless we can somehow detect this at build time, having this globally seems to be the save option.

**Comment by Lgt2x** [comment]
ok for this temporary fix, we can refactor later. I'll create an issue so we don't forget.

**Comment by Lgt2x** [comment]
See #447

**Pull request merged**
