### PR TITLE
Create new 'win' preset for Ninja (native) builds

### PR DESCRIPTION
**Pull request by tophyr**
Keep win32 and win64 using MSBuild; do not add build parallelism (it apparently causes races)

## Pull Request Type

- [ ] GitHub Workflow changes
- [ ] Documentation or Wiki changes
- [x] Build and Dependency changes
- [ ] Runtime changes
  - [ ] Render changes
  - [ ] Audio changes
  - [ ] Input changes
  - [ ] Network changes
  - [ ] Other changes

### Checklist

- [x] I have tested my changes locally and verified that they work as intended.
- [x] I have documented any new or modified functionality.
- [x] I have reviewed the changes to ensure they do not introduce any unnecessary complexity or duplicate code.
- [x] I understand that by submitting this pull request, I am agreeing to license my contributions under the project's license.

### CODE REVIEW

**Comment by tophyr** [comment]
@Lgt2x for your consideration

CI config not yet updated

**Comment by tophyr** [comment]
ok, `Windows-Ninja` CI config added and passing

**Comment by Lgt2x** [comment]
Why would we keep msbuild? ninja seems better from every perspective

**Comment by tophyr** [comment]
@Lgt2x Ninja appears incapable of producing a 32-bit binary on a 64-bit build host (or a 64-bit binary on a 32-bit build host), is why

**Comment by Lgt2x** [comment]
> @Lgt2x Ninja appears incapable of producing a 32-bit binary on a 64-bit build host (or a 64-bit binary on a 32-bit build host), is why

Actually you can. I figured out through #422  that when using the ninja generator, the only difference is that you need to load the compiler toolchain manually, whereas msbuild does it automatically when you provide the `-A` option or `architecture` Cmake preset parameter.

In order to load the toolchain, can either 1) Use [the VS script that does it for you](https://learn.microsoft.com/en-us/cpp/build/building-on-the-command-line?view=msvc-170#developer_command_file_locations), that's what the CI build do under the hood with the `msvc-dev-cmd` action. or 2) Launch the x64/x86 command prompt for VS in the start menu, which prepares the MSVC toolchain for either 32bit or 64bit.

So to get the 32bit build on a 64bit computer: Launch x86 native command prompt, and run `cmake --preset win32`, and use x64 command prompt/preset to get the 64bit build

**Comment by tophyr** [comment]
Ah, much better then.

**Pull request closed without merging**
