### PR TITLE
Fix small collection of errors

### PR DESCRIPTION
**Pull request by pzychotic**
## Pull Request Type

- [ ] GitHub Workflow changes
- [ ] Documentation or Wiki changes
- [ ] Build and Dependency changes
- [x] Runtime changes
  - [ ] Render changes
  - [ ] Audio changes
  - [ ] Input changes
  - [ ] Network changes
  - [x] Other changes

### Description

Fixed a bunch of small errors, like inverted error checks that do nothing, assignments in 'if' statements and missing va_end calls.

### Checklist

- [x] I have tested my changes locally and verified that they work as intended.
- [x] I have documented any new or modified functionality.
- [x] I have reviewed the changes to ensure they do not introduce any unnecessary complexity or duplicate code.
- [x] I understand that by submitting this pull request, I am agreeing to license my contributions under the project's license.

### CODE REVIEW

**Comment by winterheart** [comment]
That interesting things... I wonders that some of these bugs actually now "features" that we should reproduce as broken logic for playing levels...

**Review by jengelh — COMMENTED** [review]
The source code is decidedly UTF-8 (as indicated by CMakeLists.txt), so the use of U+2019 does not constitute a bug per se.

**Comment by pzychotic** [comment]
> The source code is decidedly UTF-8 (as indicated by CMakeLists.txt), so the use of U+2019 does not constitute a bug per se.

I actually get a MSVC compiler warning without that change:
Warning C4828 The file contains a character starting at offset 0x7241 that is illegal in the current source character set (codepage 65001).
Notepad++ shows this file to be ANSI, when saving as UTF-8 I get a change to that character and the warning is fixed.

**Comment by Lgt2x** [comment]
even though it's technically changing logic, most changes seem rather innocuous. The only one I'm not sure about is the one in `physics.cpp` : some mechanics could have been applied to other types of objects not intended because the `OBJ_CLUTTER` test succeeded all the time. Do you think that it's reasonable to merge as it is @winterheart ? I don't think it will cause big problems anyway

**Comment by winterheart** [comment]
I'm concerning that would change logic in level. Need to test these changes.

**Comment by jengelh** [comment]
I have given this a look, by replacing the lone `OBJ_CLUTTER` by a function `XOBJ_CLUTTER(obj)`:

```c++
bool XOBJ_CLUTTER(const object *obj) {
    if (obj->type == OBJ_CLUTTER)
        return true;
    printf("otype %u\n", obj->type);
    return false;
}
```

The path to these places suggested to me that a clutter objects needs to collide with terrain, but even on level 3 (lightning tower balls) that did not seem to readily trigger.

**Comment by pzychotic** [comment]
> I have given this a look, by replacing the lone `OBJ_CLUTTER` by a function `XOBJ_CLUTTER(obj)`:
> ...
> The path to these places suggested to me that a clutter objects needs to collide with terrain, but even on level 3 (lightning tower balls) that did not seem to readily trigger.

Nice approach!

If that change is too worrisome, I can split it out into a separate PR. Just didn't want to create a bunch of PRs for these little changes.

**Comment by jengelh** [comment]
Yeah the last two commits seem to warrant more investigation in their own right.

**Comment by pzychotic** [comment]
Updated without the possibly game play altering fixes.

**Review by Lgt2x — APPROVED** [review]
LGTM

**Pull request merged**
