### PR TITLE
Update release branch with latest commits

### PR DESCRIPTION
**Pull request by Lgt2x**
This pushes PRs #525 #523 #517 #524 #518 #519 #512 #469 #507 #516 #521 into the release branch.

To be merged before tagging the release

### CODE REVIEW

**Comment by tophyr** [comment]
lgtm, let's shipit

**Comment by Lgt2x** [comment]
> lgtm, let's shipit

so everything runs fine (scripts, multiplayer...) from the release artifact `.app`? Usage procedure is correct?

**Comment by tophyr** [comment]
Ok, I see the full range of Multiplayer options on Windows. Mac shows me Direct TCP/IP only. None of them appear to actually do anything, on either platform.

**Comment by Lgt2x** [comment]
> > so everything runs fine (scripts, multiplayer...) from the release artifact `.app`? Usage procedure is correct?
> 
> hadn't tested multiplayer - it shows me "Direct TCP/IP" as the only option but then when i hit "OK" it just exits the menu and goes back to main screen. doesn't seem like that's intended behavior.
> 
> scripts work fine in Stone Cutter, Pilot Training and Retribution. didn't play much into any of each level.
> 
> `USAGE.md` reads well and following its instructions (and installing the `.hog` appropriately) fixes the problems i was seeing before.

Ok so multiplayer definitely does not work. #515 broke multiplayer, but #524 should have fixed it. Make sure you copy the `online` directory from the artifact to the game data location.

**Comment by tophyr** [comment]
> Make sure you copy the `online` directory from the artifact to the game data location.

yep, **works fine**, i'm just an idiot again. once i copied the artifacts correctly i was able to create a TCP/IP game between my windows and mac machines and fight each other. appears to work great.

Parallax Online tries to connect, but appears to time out on windows - likely a firewall issue. Mac asks for login and password, which I don't have so am not gonna test right now.

**Comment by Lgt2x** [comment]
Sounds good, thanks for testing!

**Comment by Lgt2x** [comment]
I did a little more manual testing on Windows & Linux, looks ok

**Pull request merged**
