### PR TITLE
Fix variable name in Linux build instructions

### PR DESCRIPTION
**Pull request by Jayman2000**
## Pull Request Type

- [ ] GitHub Workflow changes
- [x] Documentation or Wiki changes
- [x] Build and Dependency changes
- [ ] Runtime changes
  - [ ] Render changes
  - [ ] Audio changes
  - [ ] Input changes
  - [ ] Network changes
  - [ ] Other changes

### Description

0b41a1b (CMake: expose BUILD_TESTNG option, rename LOGGER to ENABLE_LOGGER, 2024-04-29) had originally introduced this change. It looks like d132a1c (Merge pull request #251 from winterheart/pstring-unittests, 2024-05-01) unintentionally removed this change.

### Checklist

- [x] I have tested my changes locally and verified that they work as intended.
- [ ] I have documented any new or modified functionality.
- [x] I have reviewed the changes to ensure they do not introduce any unnecessary complexity or duplicate code.
- [x] I understand that by submitting this pull request, I am agreeing to license my contributions under the project's license.

### CODE REVIEW

**Comment by Lgt2x** [comment]
while you're at it could you also replace the wrong package `spdlog-dev` by `libspdlog-dev` in the Ubuntu install instructions? Thanks!

**Comment by Jayman2000** [comment]
> while you're at it could you also replace the wrong package `spdlog-dev` by `libspdlog-dev` in the Ubuntu install instructions? Thanks!

I actually already made that change in #259.

**Comment by JeodC** [comment]
Why would you not merge your two PRs into one if they affect the same file? This will prevent conflicts when one is merged.

**Comment by Jayman2000** [comment]
> Why would you not merge your two PRs into one if they affect the same file? This will prevent conflicts when one is merged.

I finished the other PR before I figured out what to do about this issue. The other PR’s branch’s name is `build-instructions-dependency-corrections`. In order to update that PR, I would have to rename the branch because this fix isn’t dependency-related. Unfortunately, you can’t change a PR branch’s name. Instead, you have to close the old pull request and open a new one. I didn't want to close that pull request, so I decided to open a new one with just this change.

Do you want me to create a new pull request that is a combination of both this PR and #259?

**Comment by JeodC** [comment]
Nah the explanation is fine. Thanks.

**Pull request merged**
