### PR TITLE
Add ui network settings

### PR DESCRIPTION
**Pull request by ccfly42**
## Pull Request Type

- [ ] GitHub Workflow changes
- [ ] Documentation or Wiki changes
- [ ] Build and Dependency changes
- [x] Runtime changes
  - [ ] Render changes
  - [ ] Audio changes
  - [ ] Input changes
  - [ ] Network changes
  - [x] Other changes

### Description
The commit includes a new settings window where you can change the connection speed setting.
Connection Speed ​​sets the client-side pps for multiplayer games and is currently set to default 7 pps.

I only found one useful free space in the settings under "general". If more settings are to be added in the future, 
space can be created by reducing the spacing between existing settings.

I added the settings "Lan" and "Lan+" and removed "28k", "33k" and "Cable". These are no longer up to date and would take up space in the menu.
```
old list  	new list
name pps 	name pps
28k   5		-
33k   6		-
56k   7		56k  7
ISDN  8		ISDN 8
Cable 9		-
Fast  12	Fast 12
-		Lan  20
-		Lan+ 30
```

### Screenshots (if applicable)

general
conspeed

### Checklist

- [x] I have tested my changes locally and verified that they work as intended.
- [x] I have documented any new or modified functionality.
- [x] I have reviewed the changes to ensure they do not introduce any unnecessary complexity or duplicate code.
- [x] I understand that by submitting this pull request, I am agreeing to license my contributions under the project's license.

### Additional Comments
-the maximum pps for the dedicated has been increased to 40.
-standard pps increased from 7 to 8 pps when not configured.

### CODE REVIEW

**Comment by Lgt2x** [comment]
I'm wondering, is there any situation in 2024+ where you would not want the fastest out of them all? Broadband has come a long way in 25 years, I don't know how you can get your hands on 56k or ISDN nowadays! Even "Lan" and "Lan+" are not very evocative in terms of speed

**Comment by ccfly42** [comment]
Yes, you're right. Other possibilities would be a slider, input field or we can hard code some value and close the pull.

**Comment by Lgt2x** [comment]
I'd say let's default to the highest current possible value, and we can revisit to add settings for competitive play to increase throughput/PPS if people want that!

**Comment by Lgt2x** [comment]
As a side note we could reuse the slider widget from the mouse sensitivity selection to make a PPS selector

**Comment by ccfly42** [comment]
Current suggestion:
-default pps: 30 (max)
-max dedicated pps: 40
slider

**Comment by Lgt2x** [comment]
Some servers run 40PPS, maybe the client-side maximum should be higher? I suppose modern broadband can support that. What happens when client PPS is higher than the server's?

**Comment by ccfly42** [comment]
I chose 30 pps because I know that it works without any problems (1.4 30pps mods, piccu). 
We can increase the maximum to 40 pps or more (I would be happy about it), 
but I'm not sure if 40 pps is fine as a default value, as it hasn't been tested.

The client PPS are limited per session by the server PPS. 
When connecting, the client is informed about the server PPS. 
If the client PPS is higher than the server PPS, the client is limited to the server PPS. 
So the client cannot send more PPS than the server.

If a less conservative approach is OK, we can set the default PPS to 40 or 60 and adjust it again (increase, decrease) 
in a later release if problems occur. 
If problems happens in the meantime, the server administrators can enforce lower PPS based on the server PPS.

It should be noted that the PPS should not exceed the FPS.
Furthermore, when looking through the netcode, I discovered functions that temporarily reduce the client's PPS 
in the event of problems. However, I cannot say how well these work.

**Review by Lgt2x — APPROVED** [review]
Tested again on Linux, works as intended. Thanks for the great contribution! Default and maximum value can be adjusted in the future if needed.

**Comment by Lgt2x** [comment]
> Furthermore, when looking through the netcode, I discovered functions that temporarily reduce the client's PPS
in the event of problems. However, I cannot say how well these work.

Definitely worth investigating, this area could also be documented and improved

**Pull request merged**
