### PR TITLE
More clean up

### PR DESCRIPTION
**Pull request by GravisZro**
## Pull Request Type
- [x] Build and Dependency changes

### Description
Clean up:

- Remove self-referential and unused typedefs
- Replace `PSPATHNAME_LEN` with `_MAX_PATH`
- Replace `MAX_PATH` with `_MAX_PATH`
- Remove `MAX_PATH` definition
- Fix `__stdcall` definition

### Checklist

- [x] I have tested my changes locally and verified that they work as intended.
- [x] I have documented any new or modified functionality.
- [x] I have reviewed the changes to ensure they do not introduce any unnecessary complexity or duplicate code.
- [x] I understand that by submitting this pull request, I am agreeing to license my contributions under the project's license.

### CODE REVIEW

**Comment by winterheart** [comment]
`MAX_PATH` is Windows compatibility macros. There no point renaming one C macro to other, this change is not giving any enhancement to the code.

**Comment by GravisZro** [comment]
The end result is fewer defined macros in the code. That's enough of a benefit for me.

**Review by Lgt2x — APPROVED** [review]
The change makes sense for me, we don't need 3 definitions for the exact same value. Are you ok with merging this @winterheart ?

**Comment by winterheart** [comment]
I would retain `MAX_PATH` instead of `MAX_PATH_` macros as `MAX_PATH` is part of Windows SDK:

```cpp
#ifndef MAX_PATH
#define MAX_PATH 260
#endif
```

**Comment by GravisZro** [comment]
> I would retain `MAX_PATH` instead of `MAX_PATH_` macros as `MAX_PATH` is part of Windows SDK:

I actually had questions about `MAX_PATH` versus `_MAX_PATH` and it turns out that `_MAX_PATH` is specific to their implementation of libc while `MAX_PATH` part of WinSDK. https://learn.microsoft.com/en-us/cpp/c-runtime-library/path-field-limits

This is an important distinction because theoretically `MAX_PATH` could diverge from `_MAX_PATH` which means it could be an invalid value for the libc implementation. As such, the wise move is to use the version that is associated with the functions we use, which in this case are libc functions. That is why `_MAX_PATH` is the correct choice in this particular matter.

**Comment by winterheart** [comment]
There no MAX_PATH definition other than in Windows, so defining MAX_PATH on systems that is lacks of it (all other platforms except Windows) is most natural way.

**Comment by GravisZro** [comment]
@winterheart 

Why define `MAX_PATH` at all? Why do we need a second definition for `_MAX_PATH`?

**Comment by winterheart** [comment]
Because is how it defined in Win SDK. On other platforms we need compatibility define.

**Comment by GravisZro** [comment]
> On other platforms we need compatibility define.

No, you do not because `MAX_PATH` is no longer used in the D3 code base.

**Comment by Lgt2x** [comment]
Merging with @winterheart 's approval

**Pull request merged**
