### PR TITLE
DallasFuncs pokes

### PR DESCRIPTION
**Pull request by MaddTheSane**
## Pull Request Type

- [ ] GitHub Workflow changes
- [ ] Documentation or Wiki changes
- [ ] Build and Dependency changes
- [X] Runtime changes
  - [ ] Render changes
  - [ ] Audio changes
  - [ ] Input changes
  - [ ] Network changes
  - [X] Other changes

### Description
This sets all the functions and variables in DallasFuncs.cpp as static, as well as marking them all with `[[maybe_unused]]`. marking functions and variables as `static` means that they won't be exported as public symbols by the included source files, and `[[maybe_unused]]` is because not every plug-in uses all the functions in DallasFuncs.cpp. As DallasFuncs.cpp is included in the scripts files themselves and not build individually, this shouldn't cause any issues.

### Checklist

- [X] I have tested my changes locally and verified that they work as intended.
- [X] I have documented any new or modified functionality.
- [X] I have reviewed the changes to ensure they do not introduce any unnecessary complexity or duplicate code.
- [X] I understand that by submitting this pull request, I am agreeing to license my contributions under the project's license.

### CODE REVIEW

**Comment by Arcnor** [comment]
I'm not sure we should touch this file in this way. This is parsed by D3Edit in some unknown way, and it will probably choke on those changes. Granted people can still use the old copy, but things get complicated that way. 

Changes here should probably be done in tandem with D3Edit.

**Comment by Lgt2x** [comment]
> I'm not sure we should touch this file in this way. This is parsed by D3Edit in some unknown way, and it will probably choke on those changes. Granted people can still use the old copy, but things get complicated that way.
> 
> Changes here should probably be done in tandem with D3Edit.

How hard would it be to get a D3Edit CI build going, that pulls D3 main branch as a submodule?

**Comment by Arcnor** [comment]
> How hard would it be to get a D3Edit CI build going, that pulls D3 main branch as a submodule?

Should we try to get D3Edit inside the repo first? Not sure what's the final shape we want that to look like, I remember @kevinbentley had some ideas there, but anyway, I haven't compiled D3Edit yet, but I don't think it will be difficult (talkin about the CI part, any fixes to get D3Edit to compile are unknown).

**Comment by Lgt2x** [comment]
> > How hard would it be to get a D3Edit CI build going, that pulls D3 main branch as a submodule?
> 
> Should we try to get D3Edit inside the repo first? Not sure what's the final shape we want that to look like, I remember @kevinbentley had some ideas there, but anyway, I haven't compiled D3Edit yet, but I don't think it will be difficult (talkin about the CI part, any fixes to get D3Edit to compile are unknown).

I haven't compiled D3Edit either, but I'm fine with making it part of this repo

**Comment by JeodC** [comment]
> > > How hard would it be to get a D3Edit CI build going, that pulls D3 main branch as a submodule?
> 
> > 
> 
> > Should we try to get D3Edit inside the repo first? Not sure what's the final shape we want that to look like, I remember @kevinbentley had some ideas there, but anyway, I haven't compiled D3Edit yet, but I don't think it will be difficult (talkin about the CI part, any fixes to get D3Edit to compile are unknown).
> 
> 
> 
> I haven't compiled D3Edit either, but I'm fine with making it part of this repo

+1. I know @jmarshall23 has dev editor to bring in but I don't see why we couldn't have both.

**Comment by Lgt2x** [comment]
I have an almost mature PR to build the internal editor here, hang tight!

**Comment by MaddTheSane** [comment]
Closing this, as DallasFuncs is now a separate source file.

**Pull request closed without merging**
