### PR TITLE
Generate d3-osx.hog for macOS

### PR DESCRIPTION
**Pull request by winterheart**
## Pull Request Type

- [ ] GitHub Workflow changes
- [ ] Documentation or Wiki changes
- [x] Build and Dependency changes
- [x] Runtime changes
  - [ ] Render changes
  - [ ] Audio changes
  - [ ] Input changes
  - [ ] Network changes
  - [x] Other changes

### Description

Reorganizing hog generation for Linux and macOS. Now we can generate d3-osx.hog for macOS platform.

### Checklist

- [x] I have tested my changes locally and verified that they work as intended.
- [x] I have documented any new or modified functionality.
- [x] I have reviewed the changes to ensure they do not introduce any unnecessary complexity or duplicate code.
- [x] I understand that by submitting this pull request, I am agreeing to license my contributions under the project's license.

### CODE REVIEW

**Comment by jcoby** [comment]
Confirmed working on macos

**Comment by jcoby** [comment]
> Are the changes to some of the .str files intentional? They are listed as diffs, but nothing seems to have been changed.

i noticed that as well and thought it was a github display bug. looking closer it does appear the files were changed instead of simply moved. @winterheart any idea what's going on with those files?

**Comment by MaddTheSane** [comment]
My guess is that the line ending was changed.

**Comment by winterheart** [comment]
Changes on strings are unintentional, line endings of files converted on renaming by git.

**Pull request merged**
