### PR TITLE
Save screenshots as PNG

### LINKED ISSUE #309: [Runtime Issue]: Save the screenshots as PNG instead of TGA
### Description

Screenshot logic is performed at the end of [game.cpp](https://github.com/DescentDevelopers/Descent3/blob/8d3b2f8877b35566004d7a59c8322b4daf811d17/Descent3/game.cpp#L1294C1-L1350C2). This should be modified to save as full color png instead of 16 color tga.

### PR DESCRIPTION
**Pull request by Arcnor**
## Pull Request Type

- [ ] GitHub Workflow changes
- [ ] Documentation or Wiki changes
- [x] Build and Dependency changes
- [x] Runtime changes
  - [ ] Render changes
  - [ ] Audio changes
  - [ ] Input changes
  - [ ] Network changes
  - [x] Other changes

### Description
Saves screenshots as PNG. Includes a new class for handling bitmaps called NewBitmap. I started changing the existing bitmap code, but it was a big mess because a ton of places in the code just assume `ushort` for the data returned by it, so it was a very big and messy change. Probably better to change the existing code to slowly use this new class if needed in the future, but no reason to do so for now.

### Related Issues
Fixes #309.

### Screenshots (if applicable)
Yes

### Checklist

- [x] I have tested my changes locally and verified that they work as intended.
- [x] I have documented any new or modified functionality.
- [x] I have reviewed the changes to ensure they do not introduce any unnecessary complexity or duplicate code.
- [x] I understand that by submitting this pull request, I am agreeing to license my contributions under the project's license.

### CODE REVIEW

**Review by JeodC — APPROVED** [review]
Tested and working in windows

**Comment by JeodC** [comment]
Should this be saved to a screenshots folder?

**Comment by Arcnor** [comment]
> Should this be saved to a screenshots folder?

That behavior hasn't changed, it does whatever the original did.

**Comment by JeodC** [comment]
> > Should this be saved to a screenshots folder?
> 
> That behavior hasn't changed, it does whatever the original did.

Correct, I'm asking if we should change it to avoid cluttering the root folder.

**Comment by Arcnor** [comment]
Probably better to do something like finding the Photos/Pictures folder of the computer, then storing them there or similar, we shouldn't be modifying the game folder at all. But that might be better as a separate PR, this one only dealt with the format.

**Review by Lgt2x — APPROVED** [review]
Really neat! Tested working on Linux

**Pull request merged**
