### PR TITLE
Fix debug break when starting missions with scripts

### LINKED ISSUE #605: [Runtime Issue]: Debug break when starting Pilot Training
### Build Version

v1.6 c5630268c244efb8cc1f1d967c09923915958433

### Operating System Environment

- [ ] Microsoft Windows (32-bit)
- [X] Microsoft Windows (64-bit)
- [ ] Mac OS X
- [ ] Linux (specify distribution and version below)

### CPU Environment

- [ ] x86 (32-bit Intel/AMD)
- [X] x86\_64 (64-bit Intel/AMD)
- [ ] ARM (32-bit)
- [ ] ARM64 (64-bit; sometimes called AArch64)
- [ ] Other (RISC V, PPC...)

### Game Modes Affected

- [X] Single player
- [ ] Anarchy
- [ ] Hyper-Anarchy
- [ ] Robo-Anarchy
- [ ] Team Anarchy
- [ ] Capture the Flag
- [ ] Bounty
- [ ] Entropy
- [ ] Hoard
- [ ] Monsterball
- [ ] Cooperative

### Game Environment

I’m using game data from the US Windows Dual-Jewel version of Descent 3 v1.4.

### Description

Starting the Pilot Training mission on Windows will give you this error:

Descent 3 Debug Break&NewLine;&NewLine;Int3 in C:\Users\Anon Y. Mous\Documents\Descent3-backup\Descent3\OsirisLoadandBind.cpp at line 1005.&NewLine;&NewLine;It's probably safe to continue.  Continue?&NewLine;&NewLine;Choose one of these options: Yes or No.

### Regression Status

Newest commit that doesn’t have the problem: 2d29dd4f7c76bb9474103435d587dae61b922dfb
Oldest commit that does have the problem: 09ab370821ee37cc3bea66e43a34bb21f792d503

### Steps to Reproduce

1. Start a debug build of Descent 3 on Windows.

2. Once you get to the main menu, click “New Game”.

3. If you’re prompted to select a mission, then select “Pilot Training”.

### PR DESCRIPTION
**Pull request by Jayman2000**
## Pull Request Type

- [ ] GitHub Workflow changes
- [ ] Documentation or Wiki changes
- [ ] Build and Dependency changes
- [x] Runtime changes
  - [ ] Render changes
  - [ ] Audio changes
  - [ ] Input changes
  - [ ] Network changes
  - [x] Other changes

### Description

This pull request prevents this error from happening when you start a new single player game on Windows:

Descent 3 Debug Break&NewLine;&NewLine;Int3 in C:\Users\Anon Y. Mous\Documents\Descent3-backup\Descent3\OsirisLoadandBind.cpp at line 1005.&NewLine;&NewLine;It's probably safe to continue.  Continue?&NewLine;&NewLine;Choose one of these options: Yes or No.

### Related Issues

Fixes #605.

### Checklist

- [x] I have tested my changes locally and verified that they work as intended.
- [x] I have documented any new or modified functionality.
- [x] I have reviewed the changes to ensure they do not introduce any unnecessary complexity or duplicate code.
- [x] I understand that by submitting this pull request, I am agreeing to license my contributions under the project's license.

### CODE REVIEW

**Comment by Lgt2x** [comment]
You can already rebase on #603 to get the new iteration function, I'll merge it when I get the chance to test it

**Comment by Jayman2000** [comment]
> You can already rebase on #603 to get the new iteration function, I'll merge it when I get the chance to test it

I’m going to wait until that PR gets merged, and then rebase this PR on `main`. That PR might get edited before it gets merged into `main`, and if that happens, then I would have to rebase this PR a second time.

**Comment by winterheart** [comment]
I can incorporate changes directly to #603 if you want.

**Comment by Jayman2000** [comment]
> I can incorporate changes directly to #603 if you want.

I like that idea because it would allow us to test #603 more thoroughly on Windows. Just be sure to put “Co-authored-by: Jason Yundt &lt;jason@jasonyundt.email&gt;” at the bottom of the commit message.

**Comment by winterheart** [comment]
Added relevant commit to #603.

**Pull request closed without merging**
