### PR TITLE
CMake: expose BUILD_TESTNG option, rename LOGGER to ENABLE_LOGGER

### PR DESCRIPTION
**Pull request by Lgt2x**
## Pull Request Type

- [ ] GitHub Workflow changes
- [ ] Documentation or Wiki changes
- [x] Build and Dependency changes
- [ ] Runtime changes
  - [ ] Render changes
  - [ ] Audio changes
  - [ ] Input changes
  - [ ] Network changes
  - [ ] Other changes

### Description

Expose BUILD_TESTING as a CMake option, to show up in CMake-gui and ccmake. Also rename LOGGER to ENABLE_LOGGER (options need verbs)

### CODE REVIEW

**Review by bryanperris — APPROVED** [review]

**Comment by th1000s** [comment]
`if(LOGGER)`,  maybe the compile definition name, and the README need to be adapted as well.

**Comment by Lgt2x** [comment]
> `if(LOGGER)`, maybe the compile definition name, and the README need to be adapted as well.

yes yes I pushed too promptly :)

**Comment by winterheart** [comment]
We may just change CMakeLists.txt alone and left #ifdefs in code as LOGGER as names of defines is hidden from users.

**Comment by Lgt2x** [comment]
> We may just change CMakeLists.txt alone and left #ifdefs in code as LOGGER as names of defines is hidden from users.

as you wish, I reverted the define change

**Comment by winterheart** [comment]
It's ok for merge after resolving conflicts.

**Pull request merged**
