### PR TITLE
Windows/CMake: add /MP for multi process MSBuild

### PR DESCRIPTION
**Pull request by th1000s**
### Description

"The `/MP` option can reduce the total time to compile the source files on the command line. The `/MP` option causes the compiler to create one or more copies of itself, each in a separate process."

<https://learn.microsoft.com/en-us/cpp/build/reference/mp-build-with-multiple-processes?view=msvc-170>

---

Yes, a _compile_ option which modifies the build process...

## Pull Request Type

- [ ] GitHub Workflow changes
- [ ] Documentation or Wiki changes
- [x] Build and Dependency changes
- [ ] Runtime changes

### Checklist

- [ ] I have tested my changes locally and verified that they work as intended.
- [ ] I have documented any new or modified functionality.
- [x] I have reviewed the changes to ensure they do not introduce any unnecessary complexity or duplicate code.
- [x] I understand that by submitting this pull request, I am agreeing to license my contributions under the project's license.

### CODE REVIEW

**Review by bryanperris — APPROVED** [review]
CI build time for windows took 58 seconds rather than 1 and a half minutes.

**Comment by th1000s** [comment]
Indeed, so:

- [x] I have tested my changes ~~locally~~ **_in the cloud_** and verified that they work as intended.

Is an option to disable this parallelism needed? Not sure if `-D CMAKE_CXX_FLAGS="/MP 1"` works (no Windows here, this is copied from _$WORK_). I often use `ninja -j1` so the output is cleaner, but that doesn't require a full cmake reconfigure.

**Comment by bryanperris** [comment]
> Indeed, so:
> 
> * [x]  I have tested my changes ~locally~ **_in the cloud_** and verified that they work as intended.
> 
> Is an option to disable this parallelism needed? Not sure if `-D CMAKE_CXX_FLAGS="/MP 1"` works (no Windows here, this is copied from _$WORK_). I often use `ninja -j1` so the output is cleaner, but that doesn't require a full cmake reconfigure.

Lets wait for a Windows based developer to check over this.

**Comment by bryanperris** [comment]
SaladBadger has approved the change

**Pull request merged**
